-- Every book and highlight belongs to one user. A self-hosted instance still has
-- a single account, but nothing in the schema depends on that any more.
ALTER TABLE owner RENAME TO users;
ALTER TABLE users RENAME CONSTRAINT owner_pkey TO users_pkey;
ALTER TABLE users DROP CONSTRAINT owner_id_check;

ALTER TABLE clippings DROP CONSTRAINT clippings_user_id_fkey;
ALTER TABLE clippings DROP CONSTRAINT clippings_book_id_fkey;

ALTER TABLE users ALTER COLUMN id TYPE BIGINT;
ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(
    pg_get_serial_sequence('users', 'id'),
    COALESCE((SELECT MAX(id) FROM users), 0) + 1,
    false
);
-- Emails are stored trimmed and lowercased.
ALTER TABLE users ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE clippings ALTER COLUMN user_id TYPE BIGINT;

ALTER TABLE books ADD COLUMN user_id BIGINT REFERENCES users (id) ON DELETE CASCADE;
UPDATE books SET user_id = (SELECT id FROM users ORDER BY id LIMIT 1);
-- Only reachable when no account exists, in which case no highlight refers to them.
DELETE FROM books WHERE user_id IS NULL;
ALTER TABLE books ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE books DROP CONSTRAINT books_kindle_title_key;
ALTER TABLE books ADD CONSTRAINT books_user_kindle_title_key UNIQUE (user_id, kindle_title);
ALTER TABLE books ADD CONSTRAINT books_user_id_key UNIQUE (user_id, id);

ALTER TABLE clippings
    ADD CONSTRAINT clippings_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
-- The composite key makes the database reject a highlight filed under another user's book.
ALTER TABLE clippings
    ADD CONSTRAINT clippings_user_book_fkey FOREIGN KEY (user_id, book_id) REFERENCES books (user_id, id);
